const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    position: "Sales Manager",
    phone: "+1-555-1234",
    department: "Sales",
    salary: 75000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    position: "Customer Support",
    phone: "+1-555-2345",
    department: "Support",
    salary: 48000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 3,
    name: "Carol White",
    email: "carol.white@example.com",
    position: "Marketing Specialist",
    phone: "+1-555-3456",
    department: "Marketing",
    salary: 55000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 4,
    name: "David Brown",
    email: "david.brown@example.com",
    position: "Product Manager",
    phone: "+1-555-4567",
    department: "Product",
    salary: 90000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 5,
    name: "Eva Green",
    email: "eva.green@example.com",
    position: "Software Engineer",
    phone: "+1-555-5678",
    department: "Development",
    salary: 85000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 6,
    name: "Frank Lee",
    email: "frank.lee@example.com",
    position: "QA Engineer",
    phone: "+1-555-6789",
    department: "Development",
    salary: 70000,
    active: false,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 7,
    name: "Grace Kim",
    email: "grace.kim@example.com",
    position: "HR Specialist",
    phone: "+1-555-7890",
    department: "Human Resources",
    salary: 60000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 8,
    name: "Henry Wilson",
    email: "henry.wilson@example.com",
    position: "Finance Analyst",
    phone: "+1-555-8901",
    department: "Finance",
    salary: 65000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 9,
    name: "Ivy Martinez",
    email: "ivy.martinez@example.com",
    position: "UX Designer",
    phone: "+1-555-9012",
    department: "Design",
    salary: 72000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
  {
    id: 10,
    name: "Jack Turner",
    email: "jack.turner@example.com",
    position: "DevOps Engineer",
    phone: "+1-555-0123",
    department: "Development",
    salary: 88000,
    active: false,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
  },
];

export default employees;
