const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    position: "Sales Manager",
    phone: "+1-555-1234",
    department: "Sales",
    salary: 75000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 75000,  
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    position: "Customer Support",
    phone: "+1-555-2345",
    department: "Support",
    salary: 48000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 48000, 
  },
  {
    id: 3,
    name: "Carol White",
    email: "carol.white@example.com",
    position: "Marketing Specialist",
    phone: "+1-555-3456",
    department: "Marketing",
    salary: 55000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 55000,  
  },
  {
    id: 4,
    name: "David Brown",
    email: "david.brown@example.com",
    position: "Product Manager",
    phone: "+1-555-4567",
    department: "Product",
    salary: 90000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 90000,  
  },
  {
    id: 5,
    name: "Eva Green",
    email: "eva.green@example.com",
    position: "Software Engineer",
    phone: "+1-555-5678",
    department: "Development",
    salary: 85000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 85000,  
  },
  {
    id: 6,
    name: "Frank Lee",
    email: "frank.lee@example.com",
    position: "QA Engineer",
    phone: "+1-555-6789",
    department: "Development",
    salary: 70000,
    active: false,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 0,  
  },
  {
    id: 7,
    name: "Grace Kim",
    email: "grace.kim@example.com",
    position: "HR Specialist",
    phone: "+1-555-7890",
    department: "Human Resources",
    salary: 60000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 60000, 
  },
  {
    id: 8,
    name: "Henry Wilson",
    email: "henry.wilson@example.com",
    position: "Finance Analyst",
    phone: "+1-555-8901",
    department: "Finance",
    salary: 65000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 65000,  
  },
  {
    id: 9,
    name: "Ivy Martinez",
    email: "ivy.martinez@example.com",
    position: "UX Designer",
    phone: "+1-555-9012",
    department: "Design",
    salary: 72000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 72000,  
  },
  {
    id: 10,
    name: "Jack Turner",
    email: "jack.turner@example.com",
    position: "DevOps Engineer",
    phone: "+1-555-0123",
    department: "Development",
    salary: 88000,
    active: false,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 0,  
  },

  {
    id: 11,
    name: "Karen Davis",
    email: "karen.davis@example.com",
    position: "Content Writer",
    phone: "+1-555-1111",
    department: "Marketing",
    salary: 48000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 48000,
  },
  {
    id: 12,
    name: "Leo Harris",
    email: "leo.harris@example.com",
    position: "Sales Executive",
    phone: "+1-555-2222",
    department: "Sales",
    salary: 52000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 52000,
  },
  {
    id: 13,
    name: "Mona Clark",
    email: "mona.clark@example.com",
    position: "Graphic Designer",
    phone: "+1-555-3333",
    department: "Design",
    salary: 58000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 58000,
  },
  {
    id: 14,
    name: "Nathan Scott",
    email: "nathan.scott@example.com",
    position: "Software Architect",
    phone: "+1-555-4444",
    department: "Development",
    salary: 110000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 110000,
  },
  {
    id: 15,
    name: "Olivia Young",
    email: "olivia.young@example.com",
    position: "HR Manager",
    phone: "+1-555-5555",
    department: "Human Resources",
    salary: 75000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 75000,
  },
  {
    id: 16,
    name: "Peter Adams",
    email: "peter.adams@example.com",
    position: "Finance Manager",
    phone: "+1-555-6666",
    department: "Finance",
    salary: 90000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 90000,
  },
  {
    id: 17,
    name: "Quincy Allen",
    email: "quincy.allen@example.com",
    position: "Customer Support Lead",
    phone: "+1-555-7777",
    department: "Support",
    salary: 58000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 58000,
  },
  {
    id: 18,
    name: "Rachel Evans",
    email: "rachel.evans@example.com",
    position: "QA Lead",
    phone: "+1-555-8888",
    department: "Development",
    salary: 72000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 72000,
  },
  {
    id: 19,
    name: "Steve Parker",
    email: "steve.parker@example.com",
    position: "Product Owner",
    phone: "+1-555-9999",
    department: "Product",
    salary: 95000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 95000,
  },
  {
    id: 20,
    name: "Tina Baker",
    email: "tina.baker@example.com",
    position: "Marketing Manager",
    phone: "+1-555-0000",
    department: "Marketing",
    salary: 80000,
    active: true,
    totalPresent: 0,
    halfDayLeave: 0,
    fullDayLeave: 0,
    paidLeave: 0,
    paySalary: 80000,
  },
];
export default employees;